name: Publish Terraform Files

on:
  push:
    branches:
      - master

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2.0.0
        with:
          terraform_version: 1.5.0 # Specify your Terraform version here

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          TF_VAR_some_variable: ${{ secrets.SOME_SECRET }} # Example for passing secrets

      - name: Output Terraform State
        run: |
          terraform output -json > terraform_output.json
          echo "Terraform output saved to terraform_output.json"
